{
 "title": "Project Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "data source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{node=\"$node\"}, namespace)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", node=\"$node\", namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Monitoring on Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[1m])) by (container)",
       "legendFormat": "{{container}}"
      },
      {}
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{namespace=\"$namespace\"}",
       "legendFormat": "{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Monitoring on Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receive Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{pod=\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{pod=\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pods age",
     "type": "stat",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      {
       "expr": "(kube_pod_created{pod=\"$pod\"}*1000)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Avg Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Usage by %",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "gbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\"}[1m])) / sum (machine_cpu_cores)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 23 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Disk I/O Read&Write",
     "type": "graph",
     "gridPos": { "h": 7, "w": 13, "x": 5, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(container_fs_reads_total{pod=\"$pod\"}) by (pod)",
       "legendFormat": "\"{{pod}}-read\""
      },
      {
       "expr": "sum(container_fs_writes_total{pod=\"$pod\"}) by (pod)",
       "legendFormat": "\"{{pod}}-write\""
      }
     ]
    }
   ]
  },
  {
   "title": "Monitoring on namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods restarting ATM",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Ammount of pods",
     "type": "stat",
     "gridPos": { "h": 5, "w": 11, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_info{namespace=\"$namespace\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[5m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\"}[$__rate_interval])\r\n* on (namespace,pod)\r\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\"}) by (namespace))\r\n",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[$__rate_interval])\r\n* on (namespace,pod)\r\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\"}) by (namespace))\r\n",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Amount of Deployments",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{namespace=\"$namespace\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Montoring on Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Amount of pods",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 17, "x": 3, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_info{node=\"$node\"}) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{node=\"$node\"}[5m])) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "CPU Usage by %",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*(sum(rate(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{node=\"$node\"}[5m])) by (node))",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  }
 ]
}